[project]
name = "cerebra"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "graphviz>=0.20.3",
    "groq>=0.22.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

